dist: xenial

language: generic

before_install:
  - sudo snap install --edge zola

before_script:
  - zola build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  verbose: true
